nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:3000']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'DNT' , 'User-Agent', 'X-Requested-With' ,'If-Modified-Since', 'Cache-Control', 'Range']
        max_age: 3600
    paths:
        '^/': null